title: "Mohamed BEN ALI"
description: "Data Analyst passionné par la visualisation et l’analyse de données"
remote_theme: pages-themes/modern@v0.3.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Photo de profil
avatar: "/images/PhotoPrfl.png"

# Liens sociaux
social:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/mohamed-benali/"
  - name: GitHub
    url: "https://github.com/mohamedbenali"
  - name: Email
    url: "mailto:mohamed.benali@example.com"

# Optionnel : afficher un résumé sur la page d’accueil
show_excerpts: true
